const formActionTypes = {
	SET_INPUT_TYPE: 'SET_INPUT_TYPE',
	SET_INPUT_EMAIL: 'SET_INPUT_EMAIL',
	SET_INPUT_PASSWORD: 'SET_INPUT_PASSWORD',
	SET_INPUT_FIRSTNAME: 'SET_INPUT_FIRSTNAME',
	SET_INPUT_LASTNAME: 'SET_INPUT_LASTNAME',
	SET_INPUT_PHONE: 'SET_INPUT_PHONE',



	EMAIL_VALIDATION_CHECK: 'EMAIL_VALIDATION_CHECK',

	PASSWORD_CONTAINS_MINLENGTH: 'PASSWORD_CONTAINS_MINLENGTH',
	PASSWORD_CONTAINS_UPPERCASE: 'PASSWORD_CONTAINS_UPPERCASE',
	PASSWORD_CONTAINS_SYMBOL: 'PASSWORD_CONTAINS_SYMBOLS',
	PASSWORD_CONTAINS_NUMBER: 'PASSWORD_CONTAINS_NUMBER',

	FORM_VALIDITY: 'FORM_VALIDITY',
	CLEAR_FORM_FIELDS: 'CLEAR_FORM_FIELDS'
}


export default formActionTypes;